spring:
  application:
    name: user-system
  datasource:
    url: jdbc:mysql://localhost:3306/spring?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

server:
  port: 9000

eureka:
  instance:
    hostname: user-system
  client:
    register-with-eureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/